[package]
name = "exonum-service-boilerplate"
version = "0.1.0"
authors = ["Your Name <your@email.com>"]

[dependencies]
exonum = "0.9.4"
log = "0.4.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"